name: simple_tooltip
description: A simple library for creating tooltips
version: 0.1.16
homepage: https://github.com/victorevox/simple_tooltp

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
